apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: {{ .Release.Namespace }}
data:
  API_BASE_URL: "{{ .Values.config.API_BASE_URL }}"
  LOG_LEVEL: "{{ .Values.config.LOG_LEVEL }}"
  MAX_CONNECTIONS: "{{ .Values.config.MAX_CONNECTIONS }}"
