apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{  default "http"  .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: my-app
